language: python
python: 3.5
env:  # $ tox -l | sort | xargs -I _ echo '  - TOXENV=_'
  - TOXENV=flake8
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py33-django18
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py35-django19
  - TOXENV=py35-django110
install:
  - pip install tox
script: tox
