dist: xenial
sudo: true

language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7

env:
- DJANGO=1.11
- DJANGO=2.0
- DJANGO=2.1

matrix:
  allow_failures:
  - env: TOXENV=behave-latest
  exclude:
  # Python/Django combinations that aren't officially supported
  - { env: DJANGO=1.11, python: 3.7 }
  - { env: DJANGO=2.0, python: 2.7 }
  - { env: DJANGO=2.1, python: 2.7 }
  - { env: DJANGO=2.1, python: 3.4 }

install:
- pip install tox-travis
script:
- tox

stages:
- lint
- test

jobs:
  include:
  - { stage: lint, python: 3.7, env: TOXENV=flake8 }
  - { stage: lint, python: 3.7, env: TOXENV=readme }
  - { stage: test, python: 3.7, env: TOXENV=behave-latest }
