language: python
python: 3.6
env:  # $ tox -l | sort | xargs -I _ echo '  - TOXENV=_'
  - TOXENV=flake8
  - TOXENV=py27-django18
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django18
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py36-django111
install:
  - pip install tox
script: tox
