language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django>=1.4.0,<1.5.0"
  - DJANGO="Django>=1.5.0,<1.6.0"
  - DJANGO="Django>=1.6.0,<1.7.0"
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install importlib argparse; fi
  - pip install $DJANGO
  - pip install -r requirements-dev.txt
# Test behave_django with behave :)  First, skip the failing test case
script: python manage.py behave --tags=~@failing && python tests.py
matrix:
  exclude:
   - python: "2.6"
     env: DJANGO="Django>=1.7.0,<1.8.0"
   - python: "2.6"
     env: DJANGO="Django>=1.8.0,<1.9.0"
   - python: "3.3"
     env: DJANGO="Django>=1.4.0,<1.5.0"
   - python: "3.4"
     env: DJANGO="Django>=1.4.0,<1.5.0"
