language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=django==1.4.22
  - DJANGO=django==1.5.12
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.10
  - DJANGO=django==1.8.4
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install importlib argparse; fi
  - pip install $DJANGO
  - pip install -r requirements-dev.txt
# Test behave_django with behave :)  First, skip the failing test case
script: python manage.py behave --tags=~@failing && python tests.py
matrix:
  exclude:
   - python: "2.6"
     env: DJANGO=django==1.7.10
   - python: "2.6"
     env: DJANGO=django==1.8.4
   - python: "3.3"
     env: DJANGO=django==1.4.22
   - python: "3.4"
     env: DJANGO=django==1.4.22
