language: python
env:
  - TOXENV=flake8
  - TOXENV=py26-django14
  - TOXENV=py27-django14
  - TOXENV=py26-django15
  - TOXENV=py26-django16
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
install:
  - pip install tox
script: tox
